service: StepFunctionsDemoBlog

custom:
  stage: blog
  tableName: StepFunctionDemoDynamoDB
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

provider:
  name: aws
  runtime: python3.6
  region: eu-west-2
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6
  profile: default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
      Resource: [
        "*"
      ]
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: [
        "*"
      ]

functions:
  seed-dynamodb-blog-function:
    name: seed-dynamodb-blog-function
    handler: seed_dynamodb.seed_dynamodb_handler
    timeout: 60
  get-all-users:
    name: get_all_users
    handler: get_all_users.get_all_users
  validate-name:
    name: validate_name
    handler: validate_name.validate_name
  validate-social-security:
    name: validate_social_security
    handler: validate_social_security.validate_ss
  send-email:
    name: send_email
    handler: send_email.send_email

resources:
  Resources:
    StepFunctionDemoDynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
